nscaledev/uni-kubernetes

charts/unikorn/templates/unikorn-server.yaml
charts/unikorn/values.yaml
pkg/flags/publickey.go
pkg/providers/openstack/compute.go
pkg/providers/openstack/image.go
pkg/server/handler/providers/openstack/openstack.go
pkg/server/handler/providers/openstack/options.go

We are moving away from OpenStack being the only provider, so make it so the helm/CLI interfaces are unambiguous and properly scoped.  Refactor flags so they live closer to where they will be used to stop abuse.  Add in half of the support for unikorn application credentials, rest will come next week!

Update Server Openstack Interface

---

pkg/server/middleware/logging.go
pkg/server/server.go

Quote, unquote.  But it does allow us to generate an ID in a client and display it in logs and in jaeger.  Once I figure out how to typescript this will use the full trace context specification.

Fix Request Tracing

---

pkg/server/handler/cluster/client.go
pkg/server/handler/cluster/conversion.go
pkg/server/handler/handler.go
pkg/server/middleware/openapi/openapi.go

Remove the hack that created a regional provider for each call (and hard coded at that!) and replace with a provider where it's needed and when the region name is available.

Fix Region Scoping

---

pkg/providers/openstack/provider.go
pkg/provisioners/helmapplications/clusteropenstack/provisioner.go

Obviously nothing is done yet, but we can better spot orphans when using a UID.

Add Better Provider GC Support

---

charts/unikorn/Chart.yaml
pkg/server/handler/cluster/client.go
pkg/server/handler/cluster/conversion.go
pkg/server/handler/clustermanager/client.go
pkg/server/handler/project/client.go

When an acestor doesn't exist, e.g. the organization hasn't been created yet by project creation.  Makes UI handling far simpler.

Return Empty Lists

---

charts/unikorn/Chart.yaml
pkg/providers/openstack/provider.go
pkg/provisioners/helmapplications/clusteropenstack/provisioner.go
pkg/provisioners/managers/clustermanager/provisioner.go

Add the correct roles to the openstack projects, use the correct CP version, ensure clusters tied to controller managers are deleted before we trigger the deletion of manager in order to clean up resources.

A Smorgasbord of Fixes

---

charts/unikorn/templates/unikorn-cluster-controller.yaml
go.mod
go.sum
pkg/managers/cluster/manager.go
pkg/managers/clustermanager/manager.go
pkg/providers/constants.go
pkg/providers/openstack/provider.go
pkg/provisioners/managers/cluster/provisioner.go

We can capture these in monitor and do clean up actions e.g. delete projects, provider networks etc.

Raise Events on Cluster Deletion

---

charts/unikorn/templates/unikorn-server.yaml
cmd/unikorn-server/main.go
go.mod
go.sum
pkg/providers/interfaces.go
pkg/providers/openstack/provider.go
pkg/provisioners/managers/cluster/provisioner.go
pkg/server/reaper/reaper.go

Ideally, when a cluster is finished with we want to free up resources. At the moment, that's projects, but it'll be a world of hurt if we start leaking VLANs later down the line.  As the provisioners don't know about providers, the logical place is just to wang it in server, which does, and trigger cleanups based on events from the provisioners.

Add in a Infrastructure Reaper

---

charts/unikorn/Chart.yaml
pkg/server/handler/cluster/conversion.go

For ease of use, the end user should just select a K8S version and we'll do the rest.  Obviously to do that you need to select the correct image based on version, which I utterly failed to do!

Fix Image Selection

---

charts/unikorn/Chart.yaml
go.mod
go.sum

The OIDC lib hides the underlying HTTP status code, or makes it stupidy hard to grok, so we were just returning 500.  The UI stuff should get the 403 propagated though so it can refresh the access token.  Bring in a new core library that does this.

Fix Token Expiry

---

pkg/providers/openstack/identity.go
pkg/providers/openstack/provider.go

Why you may ask, well, if the password of the main user changes, all application credentials will be invalidated, and that essentially brings down the entire region.  So to limit the blash radius we need to provision a per project user that isn't affected by global nuclear annihilation.

Provision a Per-Cluster User

---

pkg/providers/openstack/provider.go

This is a legacy thing apparently, and must get covered by either `member` or be implicit.  However, life.  Seems our provider requires it for now, so just use an explicit list if provided to remove a TODO.

Remove _member_ Role

---

charts/unikorn/templates/unikorn-server.yaml
pkg/server/server.go

Not on the main web interface for obvious reason, so you'll need to port-forward through port 6060.  I indend to move the server shiz to be shared anyway, as this is 99% the same as identity, so we'll enable it for all services at that point in time when I can do controllers too.

Enable pprof Server

---

charts/unikorn/templates/unikorn-server.yaml
pkg/server/reaper/reaper.go

Watches are flaky, and I should know this by now!  Seems the channel was closed by something, then it sat in an infinite loop constantly receiving nil.  Fix this so it restarts the watch.  Also add a field selector so that we only get the events we care about.

Fix Infinite Reaper Loop

---

pkg/providers/openstack/client.go

Tokens expire, we should allow the client to transparently reauthenticate us rather than have the region service sitting punting out errors!

Allow OpenStack Reauthentication

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/server/deployment.yaml

Server's requests are far too high and prevent scheduling on relatively constrained platforms.

Lower Memory Requests

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/applications.yaml
go.mod
go.sum
pkg/provisioners/managers/cluster/provisioner.go
pkg/provisioners/managers/clustermanager/provisioner.go
pkg/server/handler/clustermanager/client.go

Argo will now crap out fatally when it sees a resource type without the correcsponding CRD being installed yet, so we need to wait for cert-manager to be installed before installing CAPI.  Then we need to wait for all that to be working before creating the Kubernetes cluster. Then I discovered (again) the vcluster PVC is not cleaned up.

Fix ArgoCD

---

charts/kubernetes/Chart.yaml
charts/kubernetes/crds/unikorn-cloud.org_kubernetesclusters.yaml
pkg/apis/unikorn/v1alpha1/types.go
pkg/apis/unikorn/v1alpha1/zz_generated.deepcopy.go
pkg/provisioners/helmapplications/clusteropenstack/provisioner.go
pkg/provisioners/helmapplications/vcluster/config.go
pkg/provisioners/helmapplications/vcluster/provisioner.go
pkg/provisioners/helmapplications/vcluster/remotecluster.go
pkg/server/handler/cluster/client.go
pkg/server/handler/cluster/conversion.go

As they all live in the same project namespace, they need a unique release name.  Also there's an issue with the cluster GET API returning the flavor name, not the ID. Rather than doing a costly lookup, just cache it in the CRDs.

Generate vcluster Name

---

charts/kubernetes/Chart.yaml
pkg/provisioners/managers/cluster/provisioner.go
pkg/server/handler/cluster/client.go

The identity ID is not copied from the current to the updated cluster on update, so when it's deleted we end up with no ID, and thus no clean up.

Restore Identity ID on Update

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/applications.yaml
charts/kubernetes/templates/clustermanagerapplicationbundles.yaml
charts/kubernetes/templates/kubernetesclusterapplicationbundles.yaml
pkg/provisioners/helmapplications/clusteropenstack/provisioner.go

Pickup the new cluster-openstack definition which uses a common version, just like the CRD, to restore parity.  Also, while here update the resource tags so they better align with audit logs and can be used to cross reference billing and usage data by an external perty more easily. This does, however, mean that eany existing clusters will undergo a rolling upgrade to reconcile the tags, because machine templates are immuatble, seems like an optimization we may be able to fix in future... Finally to save a job, roll out the new CAPI/CAPO releases, because why not?

Upgrade Cluster(Manager) Deployment

---

pkg/server/handler/cluster/conversion.go

The OpenAPI clients don't error on non-2XX responses, so you need to manually check the status code before doing any dereferences.

Fix Cluster Conversion

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/applications.yaml
charts/kubernetes/templates/kubernetesclusterapplicationbundles.yaml
go.mod
go.sum
pkg/server/handler/cluster/client.go

This includes an addition where a server group is provisioned for the identity, we can then consume that and pass it through to CAPO, which was inevitably broken by a new CRD, so we need to include a new chart for that.

Update Region API

---

charts/kubernetes/templates/applications.yaml
charts/kubernetes/templates/kubernetesclusterapplicationbundles.yaml
pkg/server/handler/cluster/client.go

Upgrade Cilium to 1.16.  Successfully deployed a cluster and confirmed the release version is as expected:
```
% cilium version
cilium-cli: v0.16.14 compiled with go1.22.5 on darwin/arm64
cilium image (default): v1.16.0
cilium image (stable): v1.16.0
```
```
% k get kubernetescluster a7727736-c9b9-40cc-af95-c1878fe3f7c6 -n project-smnv4 -o jsonpath="{.status.conditions[].message}"
Provisioned
```

[NS-837] Bump Cilium to latest and greatest

---

go.mod
go.sum
pkg/provisioners/helmapplications/clusteropenstack/hack.go
pkg/provisioners/helmapplications/clusteropenstack/remotecluster.go
pkg/provisioners/helmapplications/openstackplugincindercsi/provisioner.go
pkg/provisioners/helmapplications/vcluster/config.go
pkg/provisioners/managers/cluster/provisioner.go
pkg/provisioners/managers/clustermanager/provisioner.go
pkg/server/handler/cluster/client.go

This propagates remote clusters and background deletion flags to the application provisioners are lot more transparently via the request context.

Use Better Provisioner Propagation

---

charts/kubernetes/templates/applications.yaml
pkg/provisioners/helmapplications/cilium/provisioner.go

This is probably missing a load of stuff!
I'm more wanting guidance on this as we need to have a way of implementing the skipProxy bits.
I've been through the testing steps but they look like they are from the old world style of testing all of this stuff! 
Is there any up-to-date guides I can go through to make sure this is fully tested?
Also I'm thinking that, for now, we should surface an option to the customer/user on whether they want cilium and if they do, automatically enable `skipPhase: ["kube-proxy"]`. something like "enable Cilium: recommended by unikorn cloud!".
I appreciate this may be missing a bunch of bits but it's a complex code base and it' my first run at it since the new design :-D

adding the skipPhases option to the cluster definitions, structs and openapi schema

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/applications.yaml
charts/kubernetes/templates/kubernetesclusterapplicationbundles.yaml
pkg/provisioners/helmapplications/clusteropenstack/provisioner.go

The hunch is that CAPI creates a token for new members to use when joining the cluster.  Shame is this is capped at 15 minutes, and when you consider Ironic provisioning does a bunch of reboots, you can easily blow this, so increase to 45m to be safe and keep it similar to the machine health check timeouts.
Additionally it appears the networking is just broken, to debug this you need to SSH in, but sadly CAPO will revert firewall rule changes, so allow these to be added if necessary.

Increase Provisioning Token Timeouts

---

charts/kubernetes/Chart.yaml
pkg/server/handler/cluster/conversion.go

Use the most EPIC control plane nodes possible, as opposed to being a penny pincher, so etcd etc doesn't melt under any circumstances. Working, at a cost, is always preferable to battling support requests.

I've Got The Power

---

charts/kubernetes/Chart.yaml
pkg/apis/unikorn/v1alpha1/helpers.go
pkg/server/handler/cluster/client.go
pkg/server/handler/cluster/conversion.go

The Kubernetes Server defaults a bunch of fields where we don't really want to expose all that complexity to the end user, but require it in the custom resource e.g. images etc.  Problem is, the defaults change, and that will randomly trigger updates which isn't great.  There are also hard coded values e.g. the control plane replicas, and you as an admin may want to scale that to 5, 7 etc. to support a specific weird workload, and obviously don't want that value reverted on an update. Long story short, if it's defaulted, preserve what's there all ready if we can, otherwise generate from the defaults.

Preserve Defaulted Values

---

charts/kubernetes/templates/applications.yaml
charts/kubernetes/templates/kubernetesclusterapplicationbundles.yaml
pkg/provisioners/helmapplications/openstackcloudprovider/provisioner.go

Creating a LoadBalancer Service without this set can result in broken behaviour when externalTrafficPolicy is set to Local, since traffic can be forwarded to nodes in a cluster which are not running the target service in question.
Also update the CCM version to the latest release.
Tested with an existing cluster as well as provisioning afresh.  In the case of the former and where LoadBalancer Services already exist, these are updated in-situ with healthmonitors created per OpenStack LB pool and no downtime.
[NHTA-182]

Create LB monitor by default, upgrade CCM version

---

pkg/provisioners/helmapplications/clusteropenstack/provisioner.go

External billing platforms may need additional data to apply costings to a cluster, e.g. the region it's in, as Ceilometer data may not provide a differentiator.  Also address the comment about the cluster type. Just layer this on rather than changing the ID to not upset the applecart too much.

Add More Server Metadata

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/applications.yaml

Some lingering smells from the old times.  Now applications are private to the service running them, there is no need for an exported field, so remove this.

Remove Old CRD Fields

---

charts/kubernetes/Chart.yaml
pkg/client/client.go

This needs to explicitly gbe given a token rather than implictly pick one up to prevent having to grant users extra privilege than they need.

Update Client Interface

---

.golangci.yaml
charts/kubernetes/Chart.yaml
pkg/server/handler/cluster/client.go
pkg/server/handler/cluster/conversion.go

Using the max was a quick workaround to undersized control planes and platform instability.  This augments that by capping resource utilization.
Fixes #141

Add CP CPU/Memory Limits

---

charts/kubernetes/Chart.yaml
go.mod
go.sum
pkg/provisioners/helmapplications/openstackcloudprovider/provisioner.go
pkg/provisioners/managers/cluster/provisioner.go

First problem is deleting the OCCM doesn't delete any load balancers, so they block deletion of the router and thus clusters never deprovision. Seond is that if someone tries to do this manually and don't know what they are doing, then chances are you'll leave a bunch of orphaned resources, namely the most scarce and expensive, the IPv4 address.  This adds a pre-deprovision hook that will get called to delete all load balancers, and yield until there are none left.
Fixes https://github.com/unikorn-cloud/region/issues/81

Fix Load Balancer Leaks

---

pkg/monitor/upgrade/cluster/check.go
pkg/monitor/upgrade/clustermanager/check.go

A breakging change was recently added to an application bundle, sadly we needed to re-instate the old bundle version for various reasons. However, the main problem here is any resources using the old bundle will get upgraded to the new one, and bascially destroy the resource due to the breaking change.  How do we prevent this?  Well everything has a semantic version, and major versions represent breaking changes, so when finding a potential upgrade target, only consider bundles with the same semantic version as the current one.

Make Auto Upgrade Semantic Version Aware

---

charts/kubernetes/Chart.yaml
pkg/provisioners/helmapplications/cilium/provisioner.go

Seeingly Cilium totally ignores what is passed to kubeadm for pod addresses, so we need to make some tweaks to allow it to do as it's told.  Now luckily, it appears the range it was hard coded to is 10.0.0.0/8.  Anything that was provisioned prior to v0.2.57 was also 10.0.0.0/8, and anything after was broken :D

Improve Cilium's IPAM

---

charts/kubernetes/templates/applications.yaml
charts/kubernetes/templates/clustermanagerapplicationbundles.yaml

Introduce the latest version of vCluster and also double the default memory limit in order to fix #188.
Tested with provisioning a new clustermanager as well as upgrading an existing one.  In the latter case there's a restart of the clustermanager (as expected) but then all services come back with no impact to managed downstream clusters.

vCluster: Upgrade to v0.23.0, increase default memory limit

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/validatingadmissionpolicies/clusterresources.yaml

Ensure labels and annotations that are expected to exist do.  We could also extend this to make them immutable, but I suspect if we need to perform a migration or some form of emergency patching this would be an impediment more than a benfit at the operations level.  One for the future though when things get more stable and mature.

Protect Resources with CEL

---

charts/kubernetes/templates/applications.yaml

The previous one is now used to upstream the changes, if they get accepted, so to prevent the branch geting deleted on merge we create a stable one.

Change ROCm Branch

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/applications.yaml
charts/kubernetes/templates/clustermanagerapplicationbundles.yaml
charts/kubernetes/templates/kubernetesclusterapplicationbundles.yaml
pkg/server/handler/cluster/conversion.go

Brings in Kubernetes API resource limits to OOM kill that process if it gets out of whack, and also enables insecure metrics for CAPI/CAPO, which live in a private vcluster, so I'm "fine" with this for now.

Upgrade CAPI and Cluster Charts

---

charts/kubernetes/templates/applications.yaml

While it deploys, it doesn't actually work as there are some KMM images that get picked up after a deploy dynamically.  While I would like to just release a Helm repo, it's done weird upstream, so we'll have to live with this until we get the proper fix upstreamed or we choose to invest a load more time...
Partially Fixes #214

Fix AMD Operator

---

go.mod
go.sum
pkg/provisioners/managers/cluster/provisioner.go
pkg/server/handler/cluster/client.go
pkg/server/handler/region/region.go

Allow API errors to be parsed and propagated up the stack to aid in debug, rather than doing super generic error handling.

API Error Propagation

---

charts/kubernetes/templates/applications.yaml

The Helm chart for the kernel module management expects the full image path for these values, and not just the tag.

Fix values for AMD GPU Operator KMM image references

---

charts/kubernetes/templates/applications.yaml
charts/kubernetes/templates/kubernetesclusterapplicationbundles.yaml

Removes the cloud provider flag primarily which is removed in Kubernetes 1.33.  Also includes the ability to do pull through caching.  This obviously triggers a rolling upgrade of the K8S control plane.
Fixes #226

Bump Cluster Chart

---

pkg/provisioners/helmapplications/virtualcluster/provisioner.go

We're allocating dedicated nodes in which the host cluster has additional resources advertised such as `nvidia.com/gpu` and `nvidia.com/mlnxnics`, so we actually want to synchronise the node itself to advertise these to the target cluster's workloads.
Similarly we need to sync host runtimeclasses to facilitate GPU workloads.

Sync runtimeClasses and real nodes for virtualclusters

---

charts/kubernetes/templates/server/clusterrole.yaml
go.mod
go.sum
pkg/provisioners/managers/cluster/provisioner.go
pkg/server/handler/cluster/client.go
pkg/server/handler/cluster/conversion.go
pkg/server/handler/handler.go
pkg/server/handler/identity/region.go
pkg/server/handler/region/region.go
pkg/server/handler/virtualcluster/client.go
pkg/server/handler/virtualcluster/conversion.go

Any handler (regions, clusters) that needed access to either the identity service or the region service would unconditionally create a client, and that would involve TLS handshakes and token exchange.  For things like clusters, they only need to update allocations on create/update/delete, not read, and only need access to flavors and images on create/update, thus there is an implicit penalty for APIs that don't need those clients.  This makes API access to those client lazy, and they will only create a client if necessary.  Secondly, much like the region service, we expect things like regions, flavors and images to be relatively static, so we can put a cache in front of these calls with an hour timeout.
The result is that on the standard "List Kubernetes Clusters" UI view, the API …

Optimize API Calls

---

charts/kubernetes/Chart.yaml
go.mod
go.sum
pkg/server/handler/region/region.go

Caching the data is all well and good, but we need to cache the client too to avoid creating a new one for listing images and flavors during cluster creation.

Add Client Caching

---

charts/kubernetes/templates/applications.yaml
pkg/provisioners/helmapplications/virtualcluster/provisioner.go

Enable HA etcd by default for virtual Kubernetes clusters.
Remove the 'embedded' option from the default application, since that is unused - Pro-only feature - and the Helm templating validation complains if you try to mix.

Enable etcd HA on virtual Kubernetes clusters

---

charts/kubernetes/crds/unikorn-cloud.org_clustermanagers.yaml
charts/kubernetes/crds/unikorn-cloud.org_kubernetesclusters.yaml
charts/kubernetes/crds/unikorn-cloud.org_virtualkubernetesclusters.yaml
charts/kubernetes/templates/monitor/clusterrole.yaml
pkg/apis/unikorn/v1alpha1/helpers.go
pkg/monitor/health/cheker.go
pkg/monitor/monitor.go

Just adding in the machinery to allow generic health checks of resources.  The interfaces we have in place act to constrain the types that can be helth checked and also provide the functions to grab applicatons from the CD layer and finally update the status conditions.

Add Health Checks Framework

---

pkg/provisioners/helmapplications/virtualcluster/provisioner.go

It's useful for any virtual cluster chart to be able to create objects based on the workload pool specs, which aren't otherwise processed by the controller.
This only really makes sense in the context of #248 (which made the vcluster chart a subchart, leaving room for the _parent_ chart to have its own templates).

Include workload pool specs in chart values

---

charts/kubernetes/templates/applications.yaml
charts/kubernetes/templates/kubernetesclusterapplicationbundles.yaml
pkg/provisioners/helmapplications/gatewayapi/provisioner.go
pkg/provisioners/managers/cluster/provisioner.go

Flip the switch on Cilium to enable Gateway API, and add a new application which deploys the CRDs since these are not included with the CNI.
Upgrades Cilium to the latest while we're at it, all defined in a new version of the bundle.

Enable Gateway API

---

go.mod
go.sum
pkg/provisioners/helmapplications/virtualcluster/provisioner.go

This uses the facility in uni-core v1.3.1(-rc) for providing metadata for the CD driver-created namespace, to propagate a VirtualKubernetesCluster's own labels to the namespace created for a virtual cluster.
This gives a clear link between that namespace and the VKC in the managing cluster, as well as a nice hook for selecting namespaces that represent virtual clusters:
kubectl get node -l unikorn-cloud.org/kind=virtualkubernetescluster
How this works:
- the packages in pkg/provisioners/helmapplications/ are used to assemble HelmApplications, by implementing generator callbacks to e.g., supply values for the Helm chart that'll be used.
- in helmapplications/virtualcluster, the generator so supplied implements `.NamespaceMetadata(...)`, which (after …

Propagate VKC labels to the remote vcluster namespace

---

pkg/server/handler/common/common.go

This PR introduces a new requirement for the project namespace selector to fix a conflict with namespaces created by SOS. 
The SOS API and controller are deployed on the same Kubernetes cluster, and SOS creates namespaces for Slinky clusters with identical labeling to the Kubernetes service. This causes a conflict during namespace reading. Adding the kind label requirement ensures proper differentiation and prevents this issue.
The same logic is already available on the compute service: https://github.com/nscaledev/uni-compute/blob/main/pkg/server/handler/common/common.go#L60

Add kind label requirement to project selector in common handler

---

charts/kubernetes/templates/cluster-manager-controller/clusterrole.yaml
pkg/managers/clustermanager/manager.go
pkg/provisioners/managers/clustermanager/provisioner.go
pkg/server/handler/cluster/client.go
pkg/server/handler/cluster/conversion.go
pkg/server/handler/cluster/conversion_test.go
pkg/server/handler/cluster/export_test.go
pkg/server/handler/clustermanager/client.go

The region service uses owner references and blocking foreground deletion, so in the interests of consistency, move to that way of working so if and when we do replace it with something else it'll be a lot easier following the same script.

Use Kubernetes Native Cascading Deletion
