README.md
charts/unikorn/Chart.yaml
charts/unikorn/templates/unikorn-server.yaml
charts/unikorn/values.yaml
pkg/server/middleware/cors/cors.go
pkg/server/middleware/openapi/authorization.go
pkg/server/middleware/openapi/openapi.go
pkg/server/middleware/openapi/schema.go
pkg/server/middleware/opentelemetry/opentelemetry.go
pkg/server/middleware/timeout/timeout.go
pkg/server/server.go

Separate the UI from the Server which makes developement easier.  It does however mean we need to deal with CORS, which isn't too bad to be honest.

Add in CORS Support

---

charts/unikorn/Chart.yaml
pkg/server/middleware/cors/cors.go

Didn't read the documentation!  Only one can be returned.

Fix Access-Control-Allow-Origin

---

charts/unikorn/Chart.yaml
pkg/provisioners/helmapplications/openstackplugincindercsi/provisioner.go
pkg/server/handler/cluster/client.go
pkg/server/handler/cluster/conversion.go

Catch a nil pointer, install the autoscaler, blah blah.

Fix Cluster Provisioning

---

README.md
pkg/providers/openstack/README.md

Get some thoughts and processes down on paper.

Openstack Region Provider Documentation

---

pkg/server/handler/cluster/client.go
pkg/server/handler/clustermanager/client.go
pkg/server/handler/project/client.go
pkg/server/handler/scoping/scoper.go

Putting it all together... start to add in scoping, so that you can only see projects and descendant resources that you have access to.

Add in Scoping

---

charts/unikorn/Chart.yaml
charts/unikorn/templates/unikorn-server.yaml
pkg/server/handler/clustermanager/client.go

I can no longer see organizations and projects, but I do get to see namespaces, and I can derive where to place things from that.

Fix Server RBAC

---

charts/unikorn/Chart.yaml
pkg/server/handler/cluster/client.go

Fix Cluster Controller Default

---

charts/unikorn/templates/applications.yaml
charts/unikorn/templates/clustermanagerapplicationbundles.yaml

Update the bundled release of vCluster to the latest and greatest.

vCluster upgrade to v0.19.5

---

charts/unikorn/templates/applications.yaml
charts/unikorn/templates/kubernetesclusterapplicationbundles.yaml

Upgrade these two components to their latest releases.

[NS-80] Bump Cilium CNI and metrics-server

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/_helpers.tpl
charts/kubernetes/templates/server/deployment.yaml
charts/kubernetes/templates/server/ingress.yaml
charts/kubernetes/values.yaml

Pick a select few values and replace with templates that can get their value from a global

Improve Helm

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/server/deployment.yaml
charts/kubernetes/values.yaml

Fix discrepency between certain uses of hostnames.

Tweak Helm

---

charts/kubernetes/crds/unikorn-cloud.org_kubernetesclusters.yaml

Add in the correct CRD and actually bump the tag.

Fix My Morning Fail

---

charts/kubernetes/Chart.yaml
pkg/server/handler/cluster/client.go

Copy the identity information from the current into the new quite simply.

Fix Cluster Update

---

pkg/server/handler/cluster/conversion.go

Because I'm so precient, we have the vendor infomation in the flavor so can disable this in a line!

Inhibit NVIDIA Operator on AMD

---

charts/kubernetes/Chart.yaml
go.mod
go.sum

See https://github.com/unikorn-cloud/identity/pull/115 for deets.

Turbo Charge Authentication

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/applications.yaml
charts/kubernetes/templates/kubernetesclusterapplicationbundles.yaml

Full explanation is in the corresponding helm chart commit.

Speculative AZ Fix

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/applications.yaml
go.mod
go.sum
pkg/provisioners/helmapplications/amdgpuoperator/provisioner.go
pkg/provisioners/helmapplications/certmanager/provisioner.go
pkg/provisioners/helmapplications/cilium/provisioner.go
pkg/provisioners/helmapplications/metricsserver/provisioner.go
pkg/provisioners/helmapplications/nvidiagpuoperator/provisioner.go
pkg/provisioners/helmapplications/openstackcloudprovider/provisioner.go
pkg/provisioners/helmapplications/openstackplugincindercsi/provisioner.go

Make this selection part of the namespace where we can to prevent hard-coding.

Move to Application Namespaces

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/kubernetesclusterapplicationbundles.yaml

82dc8ee0 has obvously not been tested based on a fresh checkout of the code.  I will find you, and I will kill you.

Developers Lie

---

charts/kubernetes/Chart.yaml
pkg/server/handler/cluster/client.go

Scale the reserved GPUs by the correct amount!

Fix GPU Allocation Bug

---

pkg/server/handler/cluster/conversion.go

While we are raising complexity from the dead, just in case...

Add Back API Whitelist and SANs

---

charts/kubernetes/Chart.yaml
charts/kubernetes/templates/applications.yaml
charts/kubernetes/templates/clustermanagerapplicationbundles.yaml

A stealth update that only changes the CAPO and ORC controllers to allow metric gathering.

Update CAPI Chart

---

pkg/provisioners/helmapplications/amdgpuoperator/provisioner.go
pkg/provisioners/helmapplications/certmanager/provisioner.go

When bringing up a baremetal cluster with the AMD GPU operator, it takes an absolute age to bring up a compute node.  ArgoCD in its inifinite wisdom decides to give up synchronization after some period of time so the cluster never gets into a provisioned state.  This fixes that by allowing cert-manager to run on the control plane.  It also caters for autoscaling from zero.  Same applies to the NFD that AMD unconditionally drags in...

Make Cert Manager Tolerate CP Nodes

---

pkg/server/handler/cluster/conversion.go

No idea why this got deleted in the first place!

Fix Image Filtering

---

pkg/provisioners/managers/virtualcluster/provisioner.go

When creating a virtual cluster, the provisioner uses ProvisionOn to install the vcluster chart on the region (underlay) cluster. The remote provisioner ultimately creates a Secret containing the kubeconfig so that ArgoCD can install to the remote cluster; that secret has a name _field_ (which ArgoCD uses as its handle), and a metadata.name (which is the name of the Secret so far as Kubernetes is concerned).
Previously, these did not line up: the name field was generated from the `VirtualKubernetesCluster` labels, while the metadata.name was the host with an optional prefix. Since the host was the same each time, each new `VirtualKubernetesCluster` would overwrite the Secret with its own name field. To ArgoCD this meant the deployment target of each virtual cluster would disappear, and it …

Scope virtual cluster deploy secrets to org

---

go.mod
go.sum
pkg/provisioners/helmapplications/openstackplugincindercsi/provisioner.go
pkg/provisioners/managers/cluster/provisioner.go
pkg/provisioners/managers/clustermanager/provisioner.go
pkg/provisioners/managers/virtualcluster/provisioner.go

Updates a few function signatures.

Update Core API
